version: "2"

services:
  backend:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      DATABASE_CONNECTION_URL: "mongodb://mongo:27017/conferences"
      PORT: 9000
      POPULATE_DATABASE: 1
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017"